create table
  public.meetings (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    title text not null,
    randomize_order boolean not null default false,
    constraint meetings_pkey primary key (id),
    constraint meetings_id_key unique (id)
  ) tablespace pg_default;