CREATE EXTENSION IF NOT EXISTS moddatetime;

create table
  public.updates (
    meeting_id bigint not null,
    started_at timestamp with time zone null,
    duration integer null,
    updated_at timestamp with time zone not null default now(),
    id bigint generated by default as identity not null,
    person_name text not null,
    constraint updates_pkey primary key (id),
    constraint updates_id_key unique (id),
    constraint updates_meeting_id_fkey foreign key (meeting_id) references meetings (id) on delete cascade
  ) tablespace pg_default;

create trigger handle_updated_at before
update on updates for each row
execute function moddatetime ('updated_at');