CREATE EXTENSION IF NOT EXISTS moddatetime;

create table
  public.people (
    meeting_id bigint not null,
    id bigint generated by default as identity not null,
    name text not null,
    "order" integer null,
    updated_at timestamp with time zone not null default now(),
    constraint people_pkey primary key (id),
    constraint people_id_key unique (id),
    constraint people_meeting_id_fkey foreign key (meeting_id) references meetings (id) on delete cascade
  ) tablespace pg_default;

create trigger handle_updated_at before
update on people for each row
execute function moddatetime ('updated_at');