create table
  public.counter (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    counter bigint null default '1'::bigint,
    updated_at timestamp with time zone not null default now(),
    constraint counter_pkey primary key (id)
  ) tablespace pg_default;