CREATE EXTENSION IF NOT EXISTS moddatetime;

create table
  public.meeting_instances (
    meeting_id bigint not null,
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    updated_at timestamp with time zone not null default now(),
    complete boolean not null default false,
    constraint meeting_instances_pkey primary key (id),
    constraint meeting_instances_id_key unique (id),
    constraint meeting_instances_meeting_id_fkey foreign key (meeting_id) references meetings (id) on delete cascade
  ) tablespace pg_default;

create trigger handle_updated_at before
update on meeting_instances for each row
execute function moddatetime ('updated_at');
